version: "3.8"
services:
  server:
    build: .
    image: jhenderson19/james-metadata-service
    ports:
      - 80:4032
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
volumes:
  db-data:
  db-config: